### ISSUE TITLE
Add matched selection

### ISSUE THREAD

**Issue by idanstark42** [FirstLegoLeague/scoring#5]
The matched for a team should be available in the API from the [tournament module](https://github.com/FirstLegoLeague/schedule) and then used in this repository to display and select a match.
### Client side
1. The selection of matched should be done through a `<select>` input, in both the `scoresheet` and the `scores` pages.
2. The selection will be disabled until a team is selected (using the `disabled` class).
3. When a team is selected, the selection will start loading, while in the background it will ask the tournament for the matches of the selected team.
4. Upon response, the selection will be enabled, and the user can select a match.
5. Matches already scored for this team, will have the score number in parenthases.
6. A missing match will be an error in the scoresheet that disables submition.
### Server side
1. The server will only contain a mock for the matches of every team for development in `server/dev_router.js`, similar to the other mocks there.
### If there is time
1. When loading the match, the team's first unfilled match will be selected automatically

**Comment by idanstark42** [comment]
@taltaub22

**Comment by taltaub22** [comment]
the endpoint is MODULE_URL/team/:team/matches

**Comment by idanstark42** [comment]
What is the structure of the JSON response?

**Comment by taltaub22** [comment]
Its basically an array of each match that the team is on

[
    {
        "_id": "5b3e5671996bdd3a187b90e5",
        "matchId": 6,
        "startTime": "2018-07-05T06:40:00.000Z",
        "endTime": "2018-07-05T06:42:00.000Z",
        "stage": "practice",
        "matchTeams": [
            {
                "teamNumber": 9,
                "tableId": 0
            },
            {
                "teamNumber": null,
                "tableId": 1
            },
            {
                "teamNumber": null,
                "tableId": 2
            },
            {
                "teamNumber": null,
                "tableId": 3
            },
            {
                "teamNumber": null,
                "tableId": 4
            },
            {
                "teamNumber": 1295,
                "tableId": 5
            },
            {
                "teamNumber": 1387,
                "tableId": 6
            },
            {
                "teamNumber": 74,
                "tableId": 7
            },
            {
                "teamNumber": 1171,
                "tableId": 8
            }
        ]
    },
    {
        "_id": "5b3e5671996bdd3a187b90ee",
        "matchId": 2,
        "startTime": "2018-07-05T08:25:00.000Z",
        "endTime": "2018-07-05T08:27:00.000Z",
        "stage": "ranking",
        "matchTeams": [
            {
                "teamNumber": 11,
                "tableId": 0
            },
            {
                "teamNumber": null,
                "tableId": 1
            },
            {
                "teamNumber": null,
                "tableId": 2
            },
            {
                "teamNumber": null,
                "tableId": 3
            },
            {
                "teamNumber": null,
                "tableId": 4
            },
            {
                "teamNumber": 1108,
                "tableId": 5
            },
            {
                "teamNumber": 1387,
                "tableId": 6
            },
            {
                "teamNumber": 442,
                "tableId": 7
            },
            {
                "teamNumber": 74,
                "tableId": 8
            }
        ]
    },
    {
        "_id": "5b3e5671996bdd3a187b90fe",
        "matchId": 18,
        "startTime": "2018-07-05T10:35:00.000Z",
        "endTime": "2018-07-05T10:37:00.000Z",
        "stage": "ranking",
        "matchTeams": [
            {
                "teamNumber": 1,
                "tableId": 0
            },
            {
                "teamNumber": null,
                "tableId": 1
            },
            {
                "teamNumber": null,
                "tableId": 2
            },
            {
                "teamNumber": null,
                "tableId": 3
            },
            {
                "teamNumber": null,
                "tableId": 4
            },
            {
                "teamNumber": 1173,
                "tableId": 5
            },
            {
                "teamNumber": 674,
                "tableId": 6
            },
            {
                "teamNumber": 51,
                "tableId": 7
            },
            {
                "teamNumber": 74,
                "tableId": 8
            }
        ]
    },
    {
        "_id": "5b3e5671996bdd3a187b9109",
        "matchId": 29,
        "startTime": "2018-07-05T11:40:00.000Z",
        "endTime": "2018-07-05T11:42:00.000Z",
        "stage": "ranking",
        "matchTeams": [
            {
                "teamNumber": 2,
                "tableId": 0
            },
            {
                "teamNumber": 74,
                "tableId": 1
            },
            {
                "teamNumber": 1173,
                "tableId": 2
            },
            {
                "teamNumber": 901,
                "tableId": 3
            },
            {
                "teamNumber": 515,
                "tableId": 4
            },
            {
                "teamNumber": null,
                "tableId": 5
            },
            {
                "teamNumber": null,
                "tableId": 6
            },
            {
                "teamNumber": null,
                "tableId": 7
            },
            {
                "teamNumber": null,
                "tableId": 8
            }
        ]
    }
]
