### ISSUE TITLE
Table name import breaks on spaces

### ISSUE THREAD

**Issue by frewes** [FirstLegoLeague/scoring#62]
If I import a scheduler file with a space in the first table name, it does not import any tables.  If there are no spaces in the first table name, it imports all tables (even if later table names include spaces).
e.g. "Table Names,Table_1,Table 2,Table 3,Table 4" imports correctly;
"Table Names,Table 1,Table 2,Table 3,Table 4" imports no tables.

Ideal behaviour - it should allow spaces in any table name.

**Comment by alanggreen** [comment]
Thanks for opening the issue. It has been fixed in this PR https://github.com/FirstLegoLeague/tournament/pull/93
